name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Dependencies
        run: |
          xcodebuild -resolvePackageDependencies
          
      - uses: ruby/setup-ruby@v1
      
      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install
        
     - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

      - name: Build and Test
        run: |
          xcodebuild \
            -workspace BlogApp.xcworkspace \
            -scheme BlogApp \
            -destination 'platform=iOS Simulator,name=iPhone 12' \
            build test
